### ISSUE TITLE
Check/validate model input from command line

### ISSUE THREAD

**Issue by ChHaeni** [oposs/agrammon#227]
- Check if necessary model variables are available in the input
- Check for non-existent specifications in the input
- Validate string entries in input

**Comment by ChHaeni** [comment]
Also: Use different validations depending on the selected model. E.g. SHL: validate for entries "a", "b" and "c", whereas LU: validate for entries "a" and "c"

**Comment by zaucker** [comment]
Implemented in release 6.0.0
