### ISSUE TITLE
What does the syntax for checking multiple conditions in a given statement look like?

### ISSUE THREAD

**Issue by ChHaeni** [oposs/agrammon#258]
E.g. how do you check for a match with any of the provided strings in a given statement?
This doesn't seem to work:
```
given ($var) {
  when "a"|"b" {
    "a or b";
  }
  default {
    "not a or b";
  }
}
```

**Comment by zaucker** [comment]
@ChHaeni `when  /a|b/` funktioniert, regex smart match

**Comment by zaucker** [comment]
`when $_ eq "a" or $_ eq "b"` würde auch gehen.

**Comment by ChHaeni** [comment]
> @ChHaeni `when /a|b/` funktioniert, regex smart match

Oh wow, das gibt mir ja ganz neue Möglichkeiten. Regex match baue ich bei Zeiten mal ein, möchte dann aber sicher wenigstens ein `warn` oder sogar `die` als default verwenden, falls die Werte sich mal ändern sollten.

Danke
