### ISSUE TITLE
Support command line options CSV output including filters

### ISSUE THREAD

**Issue by ChHaeni** [oposs/agrammon#272]
Running `agrammon.pl6 --csv --include-filters run test.csv` results in
```
Died at:
    CSV output including filters is not yet supported
      in block  at /home/christoph/repos/5_GitHub/agrammon/lib/Agrammon/UI/CommandLine.pm6 (Agrammon::UI::CommandLine) line 162
```

**Comment by jnthn** [comment]
Implementing this should be relatively easy; the trickier part is deciding how it should look in the CSV. An entry today looks like this:

```
2010v2.1_20120425;2648;Total;nh3_nanimalproduction;266.757084425741;kg N/year
```

How should we represent the breakdown and the filters in CSV?

**Comment by zaucker** [comment]
> Implementing this should be relatively easy; the trickier part is deciding how it should look in the CSV. An entry today looks like this:
> 
> 
> 
> ```
> 
> 2010v2.1_20120425;2648;Total;nh3_nanimalproduction;266.757084425741;kg N/year
> 
> ```
> 
> 
> 
> How should we represent the breakdown and the filters in CSV?

That's exactly why it is not yet implemented 😉

**Comment by zaucker** [comment]
@ChHaeni I think the CSV output so far was used for the post processing Cyrill (and perhaps you) did with the R scripts, right?
I think it might be better to use a format that supports the more complex data structure being generated when using filter groups.
I have already a JSON output being generated for the web GUI. Perhaps you could add a JSON decoder to your R scripts? We could, of course, have a custom tailored JSON export matching whatever you might need in R.
Or, you could implement the post-processing in Raku ;-)

**Comment by ChHaeni** [comment]
@zaucker I think I stick with R for that :-) But you're right, I can use the JSON output, that's fine. However, there might be others processing the model output who are not used to the JSON format.

**Comment by ChHaeni** [comment]
Maybe not nice, but how about using a second separator? E.g. `,` ?
```
2010v2.1_20120425;2648;Total;nh3_nanimalproduction,dairy_cow;266.757084425741;kg N/year
```
or brackets?
```
2010v2.1_20120425;2648;Total;nh3_nanimalproduction{dairy_cow};266.757084425741;kg N/year
```

**Comment by zaucker** [comment]
That would be entirely possible. However, you then don't really have a CSV format that can be directly "unpacked" with a CSV parser. I'd still recommend to use a standard serializer/deserializer format such as JSON available in probably most common languages. As I don't know R, I don't know into what kind of data structure this is going to be unpacked, but I am pretty confident that it will be something an R programmer will be able to deal with.
Right now there is no interface for anybody to get CSV output (except by downloading Agrammon from github). I'd suggest to implement a REST interface for whoever is going to need that. And there we can provide a format suitable for this person's needs (although I still think it should be JSON as it converts to whatever is native for them). Or do the CSV extension you suggest as worst case.
For none-programmers we'll have the PDF and Excel export from the web GUI (which could, of course, also be made available via a REST interface).

**Comment by jnthn** [comment]
>  Excel export

It occurs to me that since Excel and CSV are basically both row/column views, then figuring it out for Excel may not be entirely unrelated to figuring it out for CSV...

**Comment by zaucker** [comment]
> >  Excel export
> 
> 
> 
> It occurs to me that since Excel and CSV are basically both row/column views, then figuring it out for Excel may not be entirely unrelated to figuring it out for CSV...

True, though the existing Excel export is tailored towards human consumption and not necessarily for efficient machine processing.
But sure, parsing a rectangular matrix is certainly not rocket science.

**Comment by zaucker** [comment]
See also issue #379
