### ISSUE TITLE
Distribution auf multiple inputs in branching/flattening

### ISSUE THREAD

**Issue by zaucker** [oposs/agrammon#440]
- Inputs to be distributed in branching/flattening are marked in the `.nhd` files with the parameter `branch = true`. This would better be called `distribute = true` or something like that. If renamed, this would have to be done in both the model and the backend. Currently this parameter is always/only set on the input specifying the number of animals (which is not consistently named in the model, but that doesn't really matter).
This is the input going into the variable `$to-dist` in the backend.
- There is another parameter `adjustBranching = true` which is set (consistently?) on the inputs `dimensioning_barn` and not used so far, neither in the model nor in the backend as far as I can tell. The naming of this parameter is also not ideal.
- In a module there should be only one of these two parameters be set (not enforced I think).
- Renaming of these parameters in the model would not be a big effort, as they occur in only 9 modules and at most once each.

The problem is that in distributing those two inputs should **both** be distributed "in parallel". That is, if we have 200 cows and a barn dimension of 200 places and e.g. flatten them into two instances of 50% each, both should be 100 in each instance. Similar for branching.
The agricultural background is that NH3 emissions are depend on the number of animals. However, if there are more places in a barn than animals, those can "wander around" and there excrements are distributed over a larger area as "normal" and as emissions are also a function of surface area, there is an increase of the emissions.
Currently the generated instances would distribute animals only (200 -> 100 + 100), but barn dimension would stay at 200 for both instances and thus a correction would be applied which is actually not real/wanted.

**Comment by zaucker** [comment]
I guess it would be sufficient to have just one parameter instead of two and just distribute all inputs that have this parameter set.

**Comment by jnthn** [comment]
> Inputs to be distributed in branching/flattening are marked in the .nhd files with the parameter branch = true. This would better be called distribute = true or something like that. ...
> This is the input going into the variable $to-dist in the backend.

Given I called it "to distribute" in the backend, I guess I agree. :-)

> There is another parameter adjustBranching = true which is set (consistently?) on the inputs dimensioning_barn and not used so far, neither in the model nor in the backend as far as I can tell. The naming of this parameter is also not ideal.

Yes, seems it's not used at all in the backend.

> In a module there should be only one of these two parameters be set (not enforced I think).

I assume only one of `branching` or `adjustBranching`? When you say "in a module" what do you really mean? I think today it only really makes sense that there's one `branch = true` over all modules that together make up a particular multi-instance module? I ask because...

> The problem is that in distributing those two inputs should both be distributed "in parallel"

...this confuses me. :-) If there should only be one of `branching = true` or `adjustBranching = true` set, then how would be set up a situation where we distribute the two things in parallel?

**Comment by zaucker** [comment]
> Given I called it "to distribute" in the backend, I guess I agree. :-)

Then I'd suggest to do the rename (still needs a backend adjustment in reading the model, I think.

> > In a module there should be only one of these two parameters be set (not enforced I think).
> 
> I assume only one of `branching` or `adjustBranching`? When you say "in a module" what do you really mean? I think today it only really makes sense that there's one `branch = true` over all modules that together make up a particular multi-instance module? I ask because...
> 
> > The problem is that in distributing those two inputs should both be distributed "in parallel"
> 
> ...this confuses me. :-) If there should only be one of `branching = true` or `adjustBranching = true` set, then how would be set up a situation where we distribute the two things in parallel?

Yes, that was confusing. What I meant is, that in the current setup, only one `branch = true`, possibly together with a `adjustBranching = true` should occur in a module. With "module" I mean what in the distribution code is handled by `$taxonomy` (and not in the the `sub-taxonomy` parts). But more generally, in and below a `.nhd` file with `instances = multi` at most one `branch = true` would make any sense, possibly with one (or rethinking, I guess theoretically there could be more) of `adjustBranching = true`.

However, if we'd just use `distribute = true` we'd just treat one or many of those below one file/module with `instances = multi` all the same (distribute all of them). Where distribute means multiply with the appropriate element of `@fractions`.

**Comment by jnthn** [comment]
> Then I'd suggest to do the rename (still needs a backend adjustment in reading the model, I think.

Yes, it will need that. I figure either of us can do it.

> However, if we'd just use distribute = true we'd just treat one or many of those below one file/module with instances = multi all the same (distribute all of them). Where distribute means multiply with the appropriate element of @fractions.

But that would imply that today's `branch = true` and `adjustBranching = true` would come to have exactly the same semantics? Is that OK? I don't see any obvious problem with multiplying multiple things that we want to distribute by the same fraction, though, it's "just" making `$to-dist` be `@to-dist` and multiplying all of those inputs?

**Comment by zaucker** [comment]
As discussed by chat, I think it is as simple as you said and the original idea was just mis-leading/mis-lead.

**Comment by zaucker** [comment]
Renaming done in branch https://github.com/zaucker/agrammon/tree/ModelDistributeParameter
